version: "3"
services:

  recommendation-api:
    build:
      context: ./recommendation-api
      dockerfile: recommendation-api.dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "8M"
        max-file: "4"
